on: [push]
permissions:
  pages: write
  id-token: write
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          wget https://github.com/jgm/pandoc/releases/download/3.1.8/pandoc-3.1.8-linux-amd64.tar.gz -O pandoc.tar.gz # download
          tar xvzf pandoc.tar.gz --strip-components 1 -C . # install pandoc executable to bin/pandoc
          ./build.sh # build HTML files
      - name: Upload
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.' # upload entire repository
      - name: Deploy
        uses: actions/deploy-pages@v1
      
